### ISSUE TITLE
Error adding custom transliterators

### ISSUE THREAD

**Issue by web-patriot** [norman/babosa#24]
When I added custom transliterators, for example:

module Babosa
  module Transliterator
    class German < Latin
      APPROXIMATIONS = {
        "ä" => "ae",
        "ö" => "oe",
        "ü" => "ue",
        "Ä" => "Ae",
        "Ö" => "Oe",
        "Ü" => "Ue"
      }
    end
  end
end

I received the following warning:

...config/initializers/babosa.rb:5: warning: already initialized constant Babosa::Transliterator::German::APPROXIMATIONS
...gems/babosa-0.3.11/lib/babosa/transliterator/german.rb:5: warning: previous definition of APPROXIMATIONS was here

How can I add custom transliterators?

**Comment by norman** [comment]
The approximations are a hash, you can just add to them directly:

```ruby
Babosa::Transliterator::German::APPROXIMATIONS["ü"] = "uxu"
"Jürgen".to_slug.transliterate(:german) #=> #<Babosa::Identifier:0x007fd863c32e48 @wrapped_string="Juxurgen">
```

**Comment by web-patriot** [comment]
Well, thank you.
