### ISSUE TITLE
Should Japanese be supported?

### ISSUE THREAD

**Issue by blutorange** [norman/babosa#33]
While Chinese works well enough with 1:1 substitutions to produce something meaningful, this is impossible for Japanese. Consider the following three sentences:
- 生まれた子供たち。
- 生きる意味を見失う。
- 生意気な小僧。

Notice that they all begin with 生. But (one possible transliteration) is:
- umareta kodomo─tachi.
- ikiru imi o miushinau.
- namaiki na kozoo.

So depending on the context `生? can be either`u`,`i`, or`nama`. And it gets worse, there are more possibilities (see file below). Admittedly, there are less possibilities for other characters, but the principle stays the same.

Thus transliterating Japanese is almost as hard as transliterating it - it can be done in software only approximately (like automated translations), and it isn't going to be perfect.

Fortunately, ruby is quite popular in Japan and there are some ruby ports of some morphological analyzers, which pretty much do all the hard work. I made a simple script (mainly for private use) that illustrates how Japanese transliterations might be achieved.

Run this ruby script (more notes/comments and links to the gems at the beginning)
http://pastebin.com/hgJjqYcb

with 

> $ ruby japanese_to_ascii.rb < test_text > output

on this file
http://pastebin.com/CGTHiE58

to get this output
http://pastebin.com/aknZyH0Q

As you can see it isn't perfect, but for the most part correct and readable. So this raises the question, should Japanese be supported in the first place, seeing how hard and possibly open-ended it is...?

**Comment by norman** [comment]
I'm really not in favor of transliterating Japanese, at least not in this library. As you said, it's a large problem and one probably best left for a library dedicated to that problem exclusively. If you were to create such a library, however, I would be quite happy to make Babosa use it to provide support for Japanese.

**Comment by blutorange** [comment]
First version:

https://github.com/blutorange/hanami

My first time actually bundling a ruby script as a gem, but I tried bundling the gem and installing it, so it should (?) work. See at the end of the readme file for a quick comparison with two other transliteration tools available on the net. Just keep in mind that Japanese transliteration isn't going to be perfect without human intervention...

You are probably interested in Hanami#to_ascii, see readme and comments for more details.

**Comment by cireficc** [comment]
@blutorange Cool library :D

Japanese transliteration is an open NLP problem. Trying to add it to a gem like this will only produce many bug reports down the road that the maintainers cannot possibly fix. Thus, I say 'no' to adding support for Japanese, at least until some really smart PhD student figures out the perfect transliteration algorithm that is bug-free :)

**Comment by 6temes** [comment]
Just a note. Even if it was possible and easy, I would not use transliterated Japanese in a slug. AFAIK, for Japanese people, Japanese text in roman characters does not make sense and it's really difficult to read.
