### ISSUE TITLE
Turkish support

### ISSUE THREAD

**Issue by Hamdiakoguz** [norman/babosa#38]
Default latin transliterator is enough for Turkish support. 
Maybe it should be mentioned in readme as supported with latin or a Turkish class could be added directly inheriting from latin.
I tested with Turkish special characters (Ç,ç,Ü,ü,Ö,ö,İ,ı,Ş,ş,Ğ,ğ) and characters with circumflex (â,î,û,ê,ô):

``` ruby
"Ç,ç,Ü,ü,Ö,ö,İ,ı,Ş,ş,Ğ,ğ,â,î,û,ê,ô,Â,Î,Û,Ê,Ô".to_slug.transliterate.to_s
=> "C,c,U,u,O,o,I,i,S,s,G,g,a,i,u,e,o,A,I,U,E,O"
```

**Comment by maia** [comment]
I think it would be good to specifically support turkish, so we can do this:
````ruby
> "Ç,ç,Ü,ü,Ö,ö,İ,ı,Ş,ş,Ğ,ğ,â,î,û,ê,ô,Â,Î,Û,Ê,Ô".to_slug.transliterate(:turkish)
```
without ending up with: `NameError: uninitialized constant Babosa::Transliterator::Turkish`
