### ISSUE TITLE
Not getting installed with ruby1.9.3p194

### ISSUE THREAD

**Issue by railsfactory-bhaskararao** [norman/babosa#39]
Gem::InstallError: babosa requires Ruby version >= 2.0.0.
An error occurred while installing babosa (1.0.2), and Bundler cannot continue.
Make sure that `gem install babosa -v '1.0.2'` succeeds before bundling.

**Comment by drokia2** [comment]
I'm getting this too. In the 'Getting It' section of the readme (https://github.com/norman/babosa#getting-it). It says that 'Babosa is tested to be compatible with Ruby 1.8.7-2.0.0'. I'm also working with 1.9.3.

**Comment by drokia2** [comment]
Used version '0.3.11' and that worked for me.
