### ISSUE TITLE
cannot load such file -- unicode (LoadError)

### ISSUE THREAD

**Issue by faizalzakaria** [norman/babosa#46]
Hi there,

I saw you have already fixed this 21 days ago. I'm wondering if there is a plan to release a new version ?

Last version was like 2 years ago.

Thanks.

**Comment by digitalmoksha** [comment]
+1 

I include this in a gemspec file, so I can't just pull master.  Would it be possible to cut a release for this fix?

**Comment by lucashungaro** [comment]
+1 for a new release :)

**Comment by norman** [comment]
Hello! I've been away from this project for a long time but have some time this week to work on it and will release a new version soon that no longer depends on Unicode.
